In [1]:
print("Hello")

Hello


In [2]:
import numpy as np

#Learning Array creation method

In [3]:
array = np.array([[1,2],[8,9],[4,7]])

In [4]:
array.shape

(3, 2)

In [5]:
array.size

6

In [6]:
array

array([[1, 2],
       [8, 9],
       [4, 7]])

In [7]:
np.array({12,65,78})

array({65, 12, 78}, dtype=object)

In [8]:
z =np.zeros((3,4))

In [9]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
z.shape

(3, 4)

In [11]:
z.size

12

In [12]:
rng= np.arange((23))

In [13]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

#USING LINSPACE FOR ARRAY

In [14]:
lin=np.linspace(2,20,10)

In [15]:
lin

array([ 2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

In [16]:
rng=np.arange(99)

In [17]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [18]:
array = rng.reshape(3,33)

In [19]:
array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [20]:
array.shape

(3, 33)

In [21]:
array.size

99

In [22]:
arr = np.array([[1,2,3],[4,5,6],[7,1,0]])

In [23]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [24]:
arr.sum(axis=0) #runs top to down

array([12,  8,  9])

In [25]:
arr.sum(axis=1) #goes left to right

array([ 6, 15,  8])

In [26]:
X = np.arange(99)

In [27]:
X

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [28]:
y = X.reshape(33,3)

In [29]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [30]:
y.sum(axis=0)

array([1584, 1617, 1650])

In [31]:
y.sum(axis=1)

array([  3,  12,  21,  30,  39,  48,  57,  66,  75,  84,  93, 102, 111,
       120, 129, 138, 147, 156, 165, 174, 183, 192, 201, 210, 219, 228,
       237, 246, 255, 264, 273, 282, 291])

In [32]:
y.shape

(33, 3)

In [33]:
y.nbytes

396

In [34]:
one = np.array([2,5,7,89,0])

In [35]:
one.argmax()

3

In [36]:
one.argmin()

4

In [37]:
one.argsort()

array([4, 0, 1, 2, 3], dtype=int64)

**same thing we can do with large array but first it will arrange into 1D array then perform a task**

In [38]:
y.argmax()

98

In [39]:
y

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35],
       [36, 37, 38],
       [39, 40, 41],
       [42, 43, 44],
       [45, 46, 47],
       [48, 49, 50],
       [51, 52, 53],
       [54, 55, 56],
       [57, 58, 59],
       [60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71],
       [72, 73, 74],
       [75, 76, 77],
       [78, 79, 80],
       [81, 82, 83],
       [84, 85, 86],
       [87, 88, 89],
       [90, 91, 92],
       [93, 94, 95],
       [96, 97, 98]])

In [40]:
y.argmin()

0

In [41]:
y.argsort()
#here array got sorted as per index

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [42]:
#lets perform this on small array that can be easily demonestrated
new = np.array([[7,8,5],[65,76,88],[105,56,87]])

In [43]:
new

array([[  7,   8,   5],
       [ 65,  76,  88],
       [105,  56,  87]])

In [44]:
new.argsort()

array([[2, 0, 1],
       [0, 1, 2],
       [1, 2, 0]], dtype=int64)

In [45]:
b = new.ravel()
b

array([  7,   8,   5,  65,  76,  88, 105,  56,  87])

In [46]:
b.argsort()

array([2, 0, 1, 7, 3, 4, 8, 5, 6], dtype=int64)

In [47]:
arr1=np.array([[1,2,3],[4,5,6],[7,1,0]])
arr2=np.array([[9,2,3],[6,0,2],[2,1,3]])
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [48]:
arr2

array([[9, 2, 3],
       [6, 0, 2],
       [2, 1, 3]])

In [49]:
arr1+arr2

array([[10,  4,  6],
       [10,  5,  8],
       [ 9,  2,  3]])

In [50]:
j = arr1*arr2
j

array([[ 9,  4,  9],
       [24,  0, 12],
       [14,  1,  0]])

In [51]:
np.sqrt(j)

array([[3.        , 2.        , 3.        ],
       [4.89897949, 0.        , 3.46410162],
       [3.74165739, 1.        , 0.        ]])

In [52]:
num_float = 3.14
print("Float:", num_float)

Float: 3.14


USING BITWISE OPERATOR

In [53]:
a=2
b=3
c=a & b
c

2

In [54]:
a=2
b=3
c=a | b
c

3

In [55]:
print("The sum of two numbers",int(input("Enter 1st no.:"))+int(input("Enter 2nd no.:")))

Enter 1st no.: 5
Enter 2nd no.: 5


The sum of two numbers 10


In [56]:
import math

In [57]:
#pow refers to power here where x and y are passed as x to the power y

math.pow(234,4)

2998219536.0

In [58]:
import platform as p

In [59]:
print(p.system())

Windows


In [60]:
import math

In [61]:
r=float(input("Enter the value of r"))
area = math.pi*math.pow(r,2)
circ= math.tau*r
print("Area is :",area )
print("Circumference is :",circ)

Enter the value of r 45


Area is : 6361.725123519331
Circumference is : 282.7433388230814


In [64]:
#Now try to write this code in one single line
#import math
#print("Area of Circle:",math.pi*math.pow(r=int(input("Enter the value of radius"),2)

In [65]:
#wap where user gives name and age as input and program returns how old they will will after 100 years.
name = (input("Enter your name:"))
age = int(input("Enter your current age"))
age=100-age
year = 2024
newyear = age+2024
print("Your name is",name,"And You are left with",age,"years to become 100 year old in",newyear)

Enter your name: Aryan
Enter your current age 23


Your name is Aryan And You are left with 77 years to become 100 year old in 2101


In [66]:
x = eval('2+2')
print(x)

4


In [67]:
x = int(input("Enter the value:"))
if(x%2==0):
    print(x,"Is Even")
else:
    print(x,"Is Odd")


Enter the value: 4


4 Is Even


In [68]:
x =int(input("Enter the marks"))
if(x>90):
    print("Grade A")
elif(x>60):
    print("Grade B")
else:
    print("Grade C")
    


Enter the marks 45


Grade C


In [69]:
def check_letter_type(char):
    if char.isalpha():
        if char.isupper():
            print(f"The character '{char}' is a capital letter.")
        elif char.islower():
            print(f"The character '{char}' is a small letter.")
    else:
        print("Please enter a valid alphabet.")


# Accepting input from the user
character = input("Enter a character: ")

# Checking the type of the entered character
check_letter_type(character)


Enter a character:  dsadfw


The character 'dsadfw' is a small letter.


In [70]:
def add(a,b):
    print("The values are",a,"and",a)
    c= a+b
    print("The sum is",c)
add(3.5,2)    

The values are 3.5 and 3.5
The sum is 5.5


In [71]:
def bill(power,time,rate):
    print("The total power consumed is",power,"KW for",time,"hours at the rate of",rate,"Rupees/Unit")
    x = ((power*time)/1000)*time
    print("Your Electricity bill is",x)
bill(500,60,9)    

The total power consumed is 500 KW for 60 hours at the rate of 9 Rupees/Unit
Your Electricity bill is 1800.0


In [72]:
bill(700,98,90)

The total power consumed is 700 KW for 98 hours at the rate of 90 Rupees/Unit
Your Electricity bill is 6722.799999999999
